{
 "title": "Weather Station",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "3m",
 "templating": {
  "list": [
   {
    "name": "WeatherStation",
    "label": "Weather Station",
    "query": "Stormy Basil Cirrocumulus : Stormy_Basil_Cirrocumulus, Able Midnight Uv : Able_Midnight_Uv"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temperature AS \"actual\",\n  feels_like AS \"feels like\"\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  datetime AS \"time\",\r\n  wind_speed AS \"speed\",\r\n  wind_gust AS \"gust\"\r\nFROM WeatherStations.${WeatherStation}\r\nWHERE\r\n  $__timeFilter(datetime)\r\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  uv_index\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  pressure\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "High Temperatures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temperature AS \"actual\",\n  feels_like AS \"feels like\"\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Low Temperatures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temperature AS \"actual\",\n  feels_like AS \"feels like\"\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Rain Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "in/hr" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  precipitation\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  wind_direction\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  humidity\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Conditions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  conditions\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  temperature AS \"actual\",\n  feels_like AS \"feels like\",\n  dew_point AS \"dew point\"\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Solar Irradiance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  uv_index,\n  solar_irradiance\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  wind_speed AS \"speed\",\n  wind_gust AS \"gust\"\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Wind Speed & Direction",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  wind_speed AS \"speed\",\n  wind_direction_degrees AS \"direction\"\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  humidity\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "in/hr" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  precipitation AS \"in/hr\",\n  precipitation_accumulated AS \"total\"\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  pressure\nFROM WeatherStations.${WeatherStation}\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  }
 ]
}